cabal-version:      3.0
name:               mydocspage
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
build-type:         Simple

extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

executable mydocspage
    import:           warnings

    main-is:          Main.hs

    build-depends:
        base ^>=4.17.2.1,
        directory,
        filepath

    hs-source-dirs:   app, src
    other-modules:
        DirToNode,
        NodeTypes,
        NodeToHtml

    default-language: Haskell2010
